# Copyright (c) 2026 Danny van Dyk
#
# This file is part of the EOS project. EOS is free software;
# you can redistribute it and/or modify it under the terms of the GNU General
# Public License version 2, as published by the Free Software Foundation.
#
# EOS is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 59 Temple
# Place, Suite 330, Boston, MA  02111-1307  USA

import io
import os
from pathlib import Path
import unittest
import yaml

import eos
from eos.cli import list_constraints


_FIXTURES = Path(os.environ.get('SOURCE_DIR', Path(__file__).parents[2])) / 'eos/cli/list_constraints_TEST.d'

KNOWN_NAME       = 'R_D^(*)'
KNOWN_PREFIX     = 'B->X_sgamma'
KNOWN_CONSTRAINT = 'B->D^(*)lnu::R_D^(*)@HFLAV:2019A'


def run(*argv):
    """Runs one command line and returns its exit status together with the captured output."""
    stdout, stderr = io.StringIO(), io.StringIO()
    status = list_constraints.main([*argv], stdout=stdout, stderr=stderr)
    return status, stdout.getvalue(), stderr.getvalue()


def fixture(name):
    """Returns the lines of the expected output stored in the fixture of the given name."""
    return (_FIXTURES / name).read_text().rstrip('\n').splitlines()


class ParserTests(unittest.TestCase):

    def test_help(self):
        "'--help' exits successfully and prints the usage message."

        status, stdout, _ = run('--help')

        self.assertEqual(status, 0)
        self.assertIn('usage:', stdout)

    def test_unknown_option(self):
        "An unknown option is rejected by the parser."

        status, _, stderr = run('--no-such-option')

        self.assertEqual(status, 2)
        self.assertIn('usage:', stderr)


class ListConstraintsTests(unittest.TestCase):

    def test_filter_by_name(self):
        "Filtering by a name part reproduces the recorded output for that constraint."

        status, stdout, _ = run('-n', KNOWN_NAME)

        self.assertEqual(status, 0)
        self.assertEqual(stdout.rstrip('\n').splitlines(), fixture('r-d-star.txt'))

    def test_filter_by_prefix(self):
        "Filtering by a prefix part lists only constraints carrying that prefix."

        status, stdout, _ = run('-p', KNOWN_PREFIX)

        self.assertEqual(status, 0)
        names = [line for line in stdout.splitlines() if line and not line.startswith(' ')]
        self.assertGreater(len(names), 0)
        for name in names:
            self.assertTrue(name.startswith(f'{KNOWN_PREFIX}::'))

    def test_filters_are_combined(self):
        "Name and prefix filters select the union of their matches."

        _, by_name, _   = run('-n', KNOWN_NAME)
        _, by_prefix, _ = run('-p', KNOWN_PREFIX)
        _, by_both, _   = run('-n', KNOWN_NAME, '-p', KNOWN_PREFIX)

        self.assertEqual(len(by_both.splitlines()), len(by_name.splitlines()) + len(by_prefix.splitlines()))

    def test_without_filter(self):
        "Without a filter every constraint is listed."

        status, stdout, _ = run()

        self.assertEqual(status, 0)
        names = [line for line in stdout.splitlines() if line and not line.startswith(' ')]
        self.assertEqual(len(names), sum(1 for _ in eos.Constraints()))
        self.assertIn(KNOWN_CONSTRAINT, names)

    def test_unknown_filter(self):
        "A filter that matches no constraint lists nothing."

        status, stdout, _ = run('-n', 'no-such-constraint-name')

        self.assertEqual(status, 0)
        self.assertEqual(stdout, '')


class DumpAsYamlTests(unittest.TestCase):

    def test_known_constraint(self):
        "The dump renders the recorded YAML block for a known constraint."

        status, stdout, _ = run('-y')

        self.assertEqual(status, 0)
        self.assertIn('\n'.join(fixture('r-d-star.yaml')), stdout)

    def test_dump_is_valid_yaml(self):
        "The dump parses as a flat map holding one entry per constraint."

        status, stdout, _ = run('-y')

        self.assertEqual(status, 0)
        dump = yaml.safe_load(stdout)
        self.assertIsInstance(dump, dict)
        self.assertEqual(len(dump), sum(1 for _ in eos.Constraints()))
        self.assertEqual(dump[KNOWN_CONSTRAINT]['observables'], ['B->Dlnu::R_D', 'B->D^*lnu::R_D^*'])

    def test_header_comment(self):
        "The dump carries the header comment that points at eos-list-references."

        status, stdout, _ = run('-y')

        self.assertEqual(status, 0)
        self.assertTrue(stdout.startswith('# file generated by eos-list-constraints\n'))
        self.assertIn('eos-list-references', stdout.splitlines()[1])

    def test_filters_do_not_apply(self):
        "The dump covers every constraint even when a filter is given."

        _, unfiltered, _ = run('-y')
        _, filtered, _   = run('-y', '-n', KNOWN_NAME)

        self.assertEqual(filtered, unfiltered)


if __name__ == '__main__':
    unittest.main(verbosity=5)
