# Copyright (c) 2016-2026 Danny van Dyk
#
# This file is part of the EOS project. EOS is free software;
# you can redistribute it and/or modify it under the terms of the GNU General
# Public License version 2, as published by the Free Software Foundation.
#
# EOS is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 59 Temple
# Place, Suite 330, Boston, MA  02111-1307  USA

from __future__ import annotations

import argparse
from collections.abc import Sequence
from contextlib import redirect_stderr, redirect_stdout
import sys
import traceback
from typing import TextIO

import eos

try:
    from termcolor import colored
except ImportError:
    colored = lambda s, *args, **kwargs: s

_YAML_HEADER = [
    '# file generated by eos-list-constraints',
    '# tags used in the names of the following constraints represent references,'
    ' which can be looked up using eos-list-references',
]


def _parser():
    parser = argparse.ArgumentParser(description='List the statistical constraints implemented in EOS')
    parser.add_argument('-n', '--filter-by-name', metavar='NAME',
        help = 'Add a filter for the name part of a constraint; repeat for several names.',
        dest = 'names', action = 'append', default = []
    )
    parser.add_argument('-p', '--filter-by-prefix', metavar='PREFIX',
        help = 'Add a filter for the prefix part of a constraint; repeat for several prefixes.',
        dest = 'prefixes', action = 'append', default = []
    )
    parser.add_argument('-y', '--dump-as-yaml',
        help = 'Dump all constraints as a YAML file; the filters do not apply.',
        dest = 'dump_as_yaml', action = 'store_true', default = False
    )

    return parser


def main(argv: Sequence[str] | None = None, *, stdout: TextIO | None = None, stderr: TextIO | None = None) -> int:
    stdout = sys.stdout if stdout is None else stdout
    stderr = sys.stderr if stderr is None else stderr
    parser = _parser()
    try:
        with redirect_stdout(stdout), redirect_stderr(stderr):
            args = parser.parse_args(argv)
    except SystemExit as e:
        return int(e.code)

    with redirect_stdout(stdout), redirect_stderr(stderr):
        try:
            list_constraints(args)
        except Exception as e:
            print(colored('✖ Encountered an unrecoverable error:\n', 'red', attrs=['bold']), f'{e}', file=stdout)
            if not isinstance(e, ValueError):
                traceback.print_exception(e, e, e.__traceback__)
            return 1

    return 0


def dump_as_yaml(constraints):
    """Dump every constraint as one entry of a YAML map."""
    for line in _YAML_HEADER:
        print(line)

    for qn, entry in constraints:
        print(f'{qn.full()}:')
        for line in entry.serialize().splitlines():
            print(f'    {line}')


def print_constraint(entry):
    """Print the name, the type, and the observables of a single constraint."""
    print(entry.name().full())
    print(f'    type: {entry.type()}')

    for on in entry.observables():
        print(f'    observable: {on.full()}')

    print()


def list_constraints(args):
    """List the constraints implemented in EOS, optionally filtered by name or prefix."""
    constraints = eos.Constraints()

    if args.dump_as_yaml:
        dump_as_yaml(constraints)
        return

    names    = set(args.names)
    prefixes = set(args.prefixes)

    for qn, entry in constraints:
        if names or prefixes:
            if str(qn.prefix_part()) not in prefixes and str(qn.name_part()) not in names:
                continue

        print_constraint(entry)
