eos-evaluate \
    --kinematics s_min  0.0 \
    --kinematics s_max 12.0 \
    --observable "B->pilnu::BR;l=mu,form-factors=BCL2008" \
    --budget "FF" \
    --vary "B->pi::f_+(0)@BCL2008" \
    --vary "B->pi::b_+^1@BCL2008" \
    --vary "B->pi::b_+^2@BCL2008" \
    --budget "CKM" \
    --vary "CKM::lambda" \
    --vary "CKM::A" \
    --vary "CKM::rhobar" \
    --vary "CKM::etabar"
