eos-sample-pmc \
    --global-option model CKMScan \
    --global-option form-factors BCL2008 \
    --scan "CKM::abs(V_ub)"          2e-3   5e-3  --prior flat \
    --scan "B->pi::f_+(0)@BCL2008"   0      1     --prior flat \
    --scan "B->pi::b_+^1@BCL2008"  -20    +20     --prior flat \
    --scan "B->pi::b_+^2@BCL2008"  -20    +20     --prior flat \
    --constraint "B->pi::f_+@IKMvD-2014" \
    --constraint "B^0->pi^+lnu::BR@BaBar-2010B" \
    --constraint "B^0->pi^+lnu::BR@Belle-2010A" \
    --constraint "B^0->pi^+lnu::BR@BaBar-2012D" \
    --constraint "B^0->pi^+lnu::BR@Belle-2013A" \
    --pmc-initialize-from-file /tmp/mcmc_prerun_btopi+ff.hdf5 \
    --hc-target-ncomponents 4 \
    --hc-skip-initial 0.2 \
    --pmc-samples-per-component 500 \
    --pmc-group-by-r-value 1.5 \
    --pmc-final-samples 1000000 \
    --pmc-ignore-ess 1 \
    --pmc-relative-std-deviation-over-last-steps 0.05 4 \
    --output /tmp/pmc_monolithic_btopi+ff.hdf5
