CLEANFILES = \
	*~

MAINTAINERCLEANFILES = Makefile.in

if EOS_ENABLE_PYTHON

bin_SCRIPTS = \
	eos-analysis \
	eos-data \
	eos-figure \
	eos-list-constraints \
	eos-list-observables \
	eos-list-parameters \
	eos-list-references \
	eos-list-signal-pdfs \
	eos-mcp-server

endif

EXTRA_DIST = \
	eos-analysis \
	eos-data \
	eos-figure \
	eos-list-constraints \
	eos-list-observables \
	eos-list-parameters \
	eos-list-references \
	eos-list-signal-pdfs \
	eos-mcp-server
