# Copyright (c) 2026 Danny van Dyk
#
# This file is part of the EOS project. EOS is free software;
# you can redistribute it and/or modify it under the terms of the GNU General
# Public License version 2, as published by the Free Software Foundation.
#
# EOS is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 59 Temple
# Place, Suite 330, Boston, MA  02111-1307  USA

# These tests consume a prepared fixture tree at $SOURCE_DIR/eos/reporting_TEST.d,
# generated by eos/data/_generate_test_data.py. The fixture provides a base directory
# with the following recorded data:
#
#   reporting_TEST.d/
#     data/
#       CKM/
#         samples/        eos.data.ImportanceSamples over the parameters
#                           'CKM::abs(V_ub)' and 'B->pi::f_+(0)@BCL2008'
#                           (with weights and posterior_values)
#         mode-default/   eos.data.Mode with pvalue=0.25, global_chi2=12.0, dof=5,
#                           local_pvalues={'B->pilnu::BR': 0.5}
#       FF/
#         samples/        eos.data.ImportanceSamples over the same parameters
#                           (no mode, i.e. no goodness-of-fit)

import os
# Draw corner figures head-less; must be set before eos (and thus matplotlib) is imported.
os.environ.setdefault('MPLBACKEND', 'Agg')

import shutil
import tempfile
import unittest

import eos
import eos.data
from eos.reporting import AnalysisData, PosteriorData


# The parameter names recorded in the fixture, in order.
_PARAMETERS = ['CKM::abs(V_ub)', 'B->pi::f_+(0)@BCL2008']


class _StubMode:
    """Minimal stand-in for :class:`eos.data.Mode`, used to unit-test the mode
    selection logic without a disk fixture."""

    def __init__(self, pvalue=0.25, global_chi2=12.0, dof=5, local_pvalues=None):
        self.pvalue       = pvalue
        self.global_chi2  = global_chi2
        self.dof          = dof
        self.local_pvalues = local_pvalues


class AnalysisDataTests(unittest.TestCase):
    "Disk-driven discovery of posteriors below EOS_BASE_DIRECTORY/data/."

    _base = os.path.join(os.environ['SOURCE_DIR'], 'eos/reporting_TEST.d')

    def test_discovery(self):
        "All immediate subdirectories of data/ are discovered, in sorted order."
        ad = AnalysisData(base_directory=self._base)
        self.assertEqual(ad.names, ['CKM', 'FF'])
        self.assertEqual(len(ad), 2)
        self.assertIn('CKM', ad)
        self.assertNotIn('does-not-exist', ad)
        self.assertIsInstance(ad['CKM'], PosteriorData)
        self.assertEqual(sorted(p.name for p in ad), ['CKM', 'FF'])

    def test_missing_data_directory(self):
        "A base directory without a data/ subdirectory yields an empty container."
        empty = tempfile.mkdtemp(prefix='eos-reporting-empty-')
        self.addCleanup(shutil.rmtree, empty, ignore_errors=True)
        ad = AnalysisData(base_directory=empty)
        self.assertEqual(ad.names, [])
        self.assertEqual(len(ad), 0)

    def test_nonexistent_base_directory(self):
        "A base directory that does not exist yields an empty container (no exception)."
        ad = AnalysisData(base_directory=os.path.join(self._base, 'nope'))
        self.assertEqual(ad.names, [])


class PosteriorDataTests(unittest.TestCase):
    "Lazy, per-posterior access to recorded data."

    _base = os.path.join(os.environ['SOURCE_DIR'], 'eos/reporting_TEST.d')

    def test_samples(self):
        "Importance samples are loaded and carry the recorded parameter descriptions."
        pd = PosteriorData('CKM', base_directory=self._base)
        self.assertIsNotNone(pd.samples)
        self.assertEqual([p['name'] for p in pd.samples.varied_parameters], _PARAMETERS)
        self.assertEqual(pd.samples.samples.shape[1], len(_PARAMETERS))
        self.assertEqual(pd.samples.samples.shape[0], pd.samples.weights.shape[0])

    def test_modes(self):
        "The default mode's goodness-of-fit is exposed with the recorded values."
        pd = PosteriorData('CKM', base_directory=self._base)
        self.assertEqual(list(pd.modes.keys()), ['default'])
        self.assertTrue(pd.has_mode)
        mode = pd.mode
        self.assertIsInstance(mode, eos.data.Mode)
        self.assertAlmostEqual(mode.pvalue, 0.25)
        self.assertAlmostEqual(mode.global_chi2, 12.0)
        self.assertEqual(mode.dof, 5)
        self.assertEqual(mode.local_pvalues, {'B->pilnu::BR': 0.5})

    def test_mode_absent(self):
        "A posterior with samples but no mode."
        pd = PosteriorData('FF', base_directory=self._base)
        self.assertIsNotNone(pd.samples)
        self.assertEqual(pd.modes, {})
        self.assertIsNone(pd.mode)
        self.assertFalse(pd.has_mode)

    def test_absent_artifacts(self):
        "A posterior without any recorded data degrades gracefully to None/empty."
        pd = PosteriorData('ghost', base_directory=self._base)
        self.assertIsNone(pd.samples)
        self.assertIsNone(pd.nested)
        self.assertEqual(pd.modes, {})
        self.assertEqual(pd.predictions, {})
        self.assertIsNone(pd.mode)
        self.assertFalse(pd.has_mode)

    def test_nested_and_predictions_absent(self):
        "Absent nested-sampling results and predictions are reported as None/empty."
        pd = PosteriorData('CKM', base_directory=self._base)
        self.assertIsNone(pd.nested)
        self.assertEqual(pd.predictions, {})

    def test_lazy_without_analysis_file(self):
        "Without an analysis file, description/analysis are None but data stays accessible."
        pd = PosteriorData('CKM', base_directory=self._base)
        self.assertIsNone(pd.description)
        self.assertIsNone(pd.analysis)
        self.assertIsNotNone(pd.samples)
        self.assertEqual(list(pd.modes.keys()), ['default'])

    def test_corner_figure(self):
        "A corner figure is drawn to the requested directory and its relative name is returned."
        pd = PosteriorData('CKM', base_directory=self._base)
        outdir = tempfile.mkdtemp(prefix='eos-reporting-figure-')
        self.addCleanup(shutil.rmtree, outdir, ignore_errors=True)

        fname = pd.corner_figure(output_directory=outdir)
        self.assertEqual(fname, 'corner-CKM.pdf')
        self.assertTrue(os.path.isfile(os.path.join(outdir, fname)))

        fname_png = pd.corner_figure(output_directory=outdir, format='png', label='posterior')
        self.assertEqual(fname_png, 'corner-CKM.png')
        self.assertTrue(os.path.isfile(os.path.join(outdir, fname_png)))

    def test_corner_figure_requires_samples(self):
        "Requesting a corner figure without recorded samples raises a RuntimeError."
        pd = PosteriorData('ghost', base_directory=self._base)
        with self.assertRaises(RuntimeError):
            pd.corner_figure(output_directory=tempfile.gettempdir())

class ModeSelectionTests(unittest.TestCase):
    "Selection of the mode among possibly several recorded modes."

    _base = os.path.join(os.environ['SOURCE_DIR'], 'eos/reporting_TEST.d')

    def _posterior_with_modes(self, modes):
        # Inject the modes directly, bypassing the disk-backed cached_property, to exercise
        # only the selection logic in PosteriorData.mode.
        pd = PosteriorData('CKM', base_directory=self._base)
        pd.__dict__['modes'] = modes
        return pd

    def test_prefers_default(self):
        "The mode labelled 'default' is used when several modes exist."
        pd = self._posterior_with_modes({'default': _StubMode(pvalue=0.9), 'other': _StubMode(pvalue=0.1)})
        self.assertTrue(pd.has_mode)
        self.assertAlmostEqual(pd.mode.pvalue, 0.9)

    def test_single_non_default_mode(self):
        "A single non-default mode is used unambiguously."
        pd = self._posterior_with_modes({'foo': _StubMode(pvalue=0.4)})
        self.assertTrue(pd.has_mode)
        self.assertAlmostEqual(pd.mode.pvalue, 0.4)

    def test_ambiguous_modes(self):
        "Several non-default modes are ambiguous, so no mode is selected."
        pd = self._posterior_with_modes({'foo': _StubMode(), 'bar': _StubMode()})
        self.assertFalse(pd.has_mode)
        self.assertIsNone(pd.mode)


if __name__ == '__main__':
    unittest.main(verbosity=5)
