on:
  workflow_dispatch:

  schedule:
    - cron: '5 8 * * TUE'

name: Trigger the build of weekly development releases

jobs:
    report:
        runs-on: ubuntu-20.04
        name: Push branch ``master`` to branch ``release``
        steps:
            - name: Checkout git repository
              uses: actions/checkout@v4
              with:
                token: ${{ secrets.GITHUB_ACCESS_TOKEN }}

            - name: Fetch all branches and push
              run: |
                git remote update origin
                git push origin origin/master:release
