on:
  workflow_dispatch:

  schedule:
    - cron: '5 6 * * TUE'

name: Trigger the build of weekly development releases

jobs:
    report:
        runs-on: ubuntu-24.04
        name: Push branch ``master`` to branch ``release``
        steps:
            - name: Checkout git repository
              uses: actions/checkout@v4
              with:
                token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
                fetch-depth: 0 # download all history across all branches

            - name: Fetch all branches and push
              shell: bash
              run: |
                # determine merge base of origin/master and origin/release
                BASE=$(git merge-base origin/master origin/release)
                echo "BASE = ${BASE}"
                RELEASE=$(git rev-parse origin/release)
                echo "RELEASE = ${RELEASE}"
                MASTER=$(git rev-parse origin/master)
                echo "MASTER = ${MASTER}"
                # check if RELEASE and BASE are the same
                if [[ ${RELEASE} == ${BASE} ]] ; then
                  echo "origin/release and BASE coincide, should be able to fast-forward"
                  git push origin ${MASTER}:release
                else
                  echo "origin/release and BASE differ, would need to force push but will not do it"
                fi
